Business Understanding

**Data Understanding**

In [ ]:
import pandas as pd

data = {
    "review": [
        "I really loved this phone",
        "Amazing phone with excellent camera",
        "The camera quality is fantastic",
        "I am very happy with this product",
        "This phone is excellent",
        "I love the battery life",

        "The phone is okay",
        "It is an average product",
        "The phone is neither good nor bad",
        "The product is fine",
        "The phone works normally",
        "It is an ordinary phone",

        "I hate this phone",
        "The battery is very bad",
        "Terrible product and poor quality",
        "I am disappointed with this phone",
        "The camera quality is horrible",
        "Very bad experience"
    ],

    "sentiment": [
        "Positive",
        "Positive",
        "Positive",
        "Positive",
        "Positive",
        "Positive",

        "Neutral",
        "Neutral",
        "Neutral",
        "Neutral",
        "Neutral",
        "Neutral",

        "Negative",
        "Negative",
        "Negative",
        "Negative",
        "Negative",
        "Negative"
    ]
}

df = pd.DataFrame(data)

print(df.head())

                                review sentiment
0            I really loved this phone  Positive
1  Amazing phone with excellent camera  Positive
2      The camera quality is fantastic  Positive
3    I am very happy with this product  Positive
4              This phone is excellent  Positive

**Data Preparation**

In [ ]:
X = df["review"]
y = df["sentiment"]

**Train test Split**

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

Data Preprocessing

In [ ]:
import re

def preprocess_text(text):

    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove punctuation
    text = re.sub(r"[^a-zA-Z\s]", "", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [ ]:
X_train_clean = X_train.apply(preprocess_text)
X_test_clean = X_test.apply(preprocess_text)
X_test_clean

7              it is an average product
16       the camera quality is horrible
4               this phone is excellent
3     i am very happy with this product
Name: review, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer()

# Learn vocabulary from training data
X_train_tfidf = vectorizer.fit_transform(X_train_clean)

# Convert test data using same vocabulary
X_test_tfidf = vectorizer.transform(X_test_clean)

print("\nTF-IDF shape:")
print(X_train_tfidf.shape)

TF-IDF shape:
(14, 35)

**Model Building**

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train_tfidf, y_train)

LogisticRegression()

**Model Prediction**

In [ ]:
y_pred = model.predict(X_test_tfidf)

Model Testing

In [ ]:
results = pd.DataFrame({
    "Review": X_test.values,
    "Actual": y_test.values,
    "Predicted": y_pred
})

results

                              Review    Actual Predicted
0           It is an average product   Neutral   Neutral
1     The camera quality is horrible  Negative  Positive
2            This phone is excellent  Positive  Negative
3  I am very happy with this product  Positive  Negative

In [ ]:
new_reviews = [
    "I absolutely love this phone",
    "The phone is okay",
    "The battery is terrible",
    "Amazing camera quality",
    "Very disappointing product"
]

# Preprocess
new_reviews_clean = [
    preprocess_text(review)
    for review in new_reviews
]

# Convert to TF-IDF
new_reviews_tfidf = vectorizer.transform(new_reviews_clean)

# Predict
predictions = model.predict(new_reviews_tfidf)
print("\nNew Review Predictions:")

for review, prediction in zip(new_reviews, predictions):

    print(
        review,
        " --> ",
        prediction
    )

New Review Predictions:
I absolutely love this phone  -->  Negative
The phone is okay  -->  Neutral
The battery is terrible  -->  Negative
Amazing camera quality  -->  Positive
Very disappointing product  -->  Negative